In [2]:
try:
    import sim
except:
    print ('--------------------------------------------------------------')
    print ('"sim.py" could not be imported. This means very probably that')
    print ('either "sim.py" or the remoteApi library could not be found.')
    print ('Make sure both are in the same folder as this file,')
    print ('or appropriately adjust the file "sim.py"')
    print ('--------------------------------------------------------------')
    print ('')
  

import time
import numpy as np

def Rz(theta):
  
    return np.array([[ np.cos(theta), -np.sin(theta), 0 ],
                      [ np.sin(theta), np.cos(theta) , 0 ],
                      [ 0            , 0             , 1 ]])

# Holonômico (robotino)

In [15]:
####################################################################################
#                                                                                  #
#                 LEMBRE-SE QUE A SIMULAÇÃO DEVE ESTAR EM EXECUÇÃO!                #
#                                                                                  #
####################################################################################

# Velocidade angular máxima 8.883475303649902
# Velocidade linear máxima 0.6717071533203125
# Velocidade linear máxima 0.28
# 1.550555944442749 Tempo para acelerar de 0 até 0.6253740787506104, velocidade definida de 0.65 m/s
# 2.447660446166992 Tempo para acelerar de 0 até 3.26932430267334, velocidade definida de pi radianos/s

print ('Program started')
sim.simxFinish(-1) # just in case, close all opened connections
clientID=sim.simxStart('127.0.0.1',19999,True,True,5000,5) # Connect to CoppeliaSim

if clientID!=-1:
    print ('Connected to remote API server')

    robotname = 'robotino'
    returnCode, robotHandle = sim.simxGetObjectHandle(clientID, robotname, sim.simx_opmode_oneshot_wait)     
                 
    returnCode, wheel1 = sim.simxGetObjectHandle(clientID, 'wheel0_joint', sim.simx_opmode_oneshot_wait)
    returnCode, wheel2 = sim.simxGetObjectHandle(clientID, 'wheel1_joint', sim.simx_opmode_oneshot_wait)
    returnCode, wheel3 = sim.simxGetObjectHandle(clientID, 'wheel2_joint', sim.simx_opmode_oneshot_wait)
           
    # Robotino
    L = 0.135   # Metros
    r = 0.040   # Metros
               
    # Cinemática Direta
    Mdir = np.array([[-r/np.sqrt(3), 0, r/np.sqrt(3)], [r/3, (-2*r)/3, r/3], [r/(3*L), r/(3*L), r/(3*L)]])
                       
    q = np.array([0, 0, 0])
    
    # Lembrar de habilitar o 'Real-time mode'
    t = 0
    lastTime = time.time()
    while t <= 10:
        
        now = time.time()
        dt = now - lastTime
        
        # Cinemática Direta
        # u = [np.deg2rad(45), np.deg2rad(0), np.deg2rad(-45)]
        
        # Velocidade desejada (x, y, w)    
        qdot = np.array([0.1, 0.1, 0.5])
        
        #qdot = np.array([0, .3, 0])
        
        # Cinemática Inversa
        # w1, w2, w3
        Minv = np.linalg.inv(Rz(q[2]) @ Mdir)
        u = Minv @ qdot
        print(u)

        # Enviando velocidades
        sim.simxSetJointTargetVelocity(clientID, wheel1, u[0], sim.simx_opmode_streaming)
        sim.simxSetJointTargetVelocity(clientID, wheel2, u[1], sim.simx_opmode_streaming)
        sim.simxSetJointTargetVelocity(clientID, wheel3, u[2], sim.simx_opmode_streaming) 

        #Verificação da velocidade real do Robotino     
        returnCode, linearVelocity, angularVelocity = sim.simxGetObjectVelocity(clientID, robotHandle, sim.simx_opmode_streaming)
        print(linearVelocity[0], linearVelocity[1], angularVelocity[2])
        
        q = q + (Rz(q[2]) @ Mdir @ u)*dt
        
        t = t + dt        
        lastTime = now
        
    print('==> ', t, q[:2], np.rad2deg(q[2]))
    
    returnCode, pos = sim.simxGetObjectPosition(clientID, robotHandle, -1, sim.simx_opmode_oneshot_wait)        
    print('Pos: ', pos)

    returnCode, ori = sim.simxGetObjectOrientation(clientID, robotHandle, -1, sim.simx_opmode_oneshot_wait)
    print('Ori: ', np.rad2deg(ori))
        
    sim.simxSetJointTargetVelocity(clientID, wheel1, 0, sim.simx_opmode_oneshot_wait)
    sim.simxSetJointTargetVelocity(clientID, wheel2, 0, sim.simx_opmode_oneshot_wait)
    sim.simxSetJointTargetVelocity(clientID, wheel3, 0, sim.simx_opmode_oneshot_wait)
        
    # Now close the connection to CoppeliaSim:
    sim.simxFinish(clientID)
    
else:
    print ('Failed connecting to remote API server')
    
print ('Program ended')

Program started
Connected to remote API server
[ 0.77243649 -0.8125      5.10256351]
0.0 0.0 0.0
[ 0.77243649 -0.8125      5.10256351]
0.0 0.0 0.0
[ 0.76900829 -0.80998879  5.10348049]
0.0 0.0 0.0
[ 0.76729088 -0.80872955  5.10393867]
0.0 0.0 0.0
[ 0.76729088 -0.80872955  5.10393867]
0.0 0.0 0.0
[ 0.76558306 -0.80747655  5.10439349]
0.0 0.0 0.0
[ 0.76558306 -0.80747655  5.10439349]
0.0 0.0 0.0
[ 0.76387059 -0.80621934  5.10484876]
0.0 0.0 0.0
[ 0.76215875 -0.80496181  5.10530305]
0.0 0.0 0.0
[ 0.76215875 -0.80496181  5.10530305]
0.0 0.0 0.0
[ 0.76044796 -0.80370424  5.10575628]
0.0 0.0 0.0
[ 0.75873334 -0.80244305  5.10620971]
0.0 0.0 0.0
[ 0.75702465 -0.80118543  5.10666078]
0.0 0.0 0.0
[ 0.75702465 -0.80118543  5.10666078]
0.0 0.0 0.0
[ 0.75531415 -0.79992568  5.10711153]
0.0 0.0 0.0
[ 0.75360268 -0.79866441  5.10756174]
0.0 0.0 0.0
[ 0.75189062 -0.79740192  5.1080113 ]
0.0 0.0 0.0
[ 0.75189062 -0.79740192  5.1080113 ]
0.0 0.0 0.0
[ 0.75018164 -0.7961409   5.10845925]
0.0 0.0 0.0
[ 0

# Holonômico (robotino) alterado

In [31]:
####################################################################################
#                                                                                  #
#                 LEMBRE-SE QUE A SIMULAÇÃO DEVE ESTAR EM EXECUÇÃO!                #
#                                                                                  #
####################################################################################

# Velocidade angular máxima 8.883475303649902
# Velocidade linear máxima 0.6717071533203125
# 1.550555944442749 Tempo para acelerar de 0 até 0.6253740787506104, velocidade definida de 0.65 m/s
# 2.447660446166992 Tempo para acelerar de 0 até 3.26932430267334, velocidade definida de pi radianos/s

print ('Program started')
sim.simxFinish(-1) # just in case, close all opened connections
clientID=sim.simxStart('127.0.0.1',19999,True,True,5000,5) # Connect to CoppeliaSim

if clientID!=-1:
    print ('Connected to remote API server')

    robotname = 'robotino'
    returnCode, robotHandle = sim.simxGetObjectHandle(clientID, robotname, sim.simx_opmode_oneshot_wait)     
                 
    returnCode, wheel1 = sim.simxGetObjectHandle(clientID, 'wheel0_joint', sim.simx_opmode_oneshot_wait)
    returnCode, wheel2 = sim.simxGetObjectHandle(clientID, 'wheel1_joint', sim.simx_opmode_oneshot_wait)
    returnCode, wheel3 = sim.simxGetObjectHandle(clientID, 'wheel2_joint', sim.simx_opmode_oneshot_wait)
           
    # Robotino
    L = 0.135   # Metros
    r = 0.040   # Metros
               
    # Cinemática Direta
    Mdir = np.array([[-r/np.sqrt(3), 0, r/np.sqrt(3)], [r/3, (-2*r)/3, r/3], [r/(3*L), r/(3*L), r/(3*L)]])
                       
    q = np.array([0, 0, 0])

    error = np.array([0, 0, 0])
    lastError = np.array([0, 0, 0])
    cumError = np.array([0, 0, 0])
    lastTime = 0
    
    # Lembrar de habilitar o 'Real-time mode'
    t = 0
    lastTime = time.time()
    while t <= 6.5:
        time.sleep(0.005)
        now = time.time()
        dt = now - lastTime
        
        # Velocidade desejada (x, y, w)    
        qdot = np.array([10, 0, 0])

        returnCode, linearVelocity, angularVelocity = sim.simxGetObjectVelocity(clientID, robotHandle, sim.simx_opmode_streaming)
        setPoint=np.array([linearVelocity[0], linearVelocity[1], angularVelocity[2]])
        print(setPoint)
        
            
        # Error        
        error = qdot - setPoint
        dError = (error - lastError) /dt
        cumError = cumError + error * dt
        # print(f"error: {error, dError, cumError}")

        # Proporcional
        kp = 0.4
        up = kp*error
        
        # Derivativo
        kd = 0.5
        ud = kd*dError
        
        # Integral
        ki = .01
        ui = ki*cumError
    
        # Controller
        qdot = qdot - (up + ud + ui)
        # print(f"qdot {qdot}")
        
        # Cinemática Direta
        # u = [np.deg2rad(45), np.deg2rad(0), np.deg2rad(-45)]
        
        # Cinemática Inversa-
        # w1, w2, w3
        Minv = np.linalg.inv(Rz(q[2]) @ Mdir)
        u = Minv @ qdot

        # Enviando velocidades
        sim.simxSetJointTargetVelocity(clientID, wheel1, u[0], sim.simx_opmode_streaming)
        sim.simxSetJointTargetVelocity(clientID, wheel2, u[1], sim.simx_opmode_streaming)
        sim.simxSetJointTargetVelocity(clientID, wheel3, u[2], sim.simx_opmode_streaming)      
        
        q = q + (Rz(q[2]) @ Mdir @ u)*dt
        
        t = t + dt        
        lastTime = now
        lastError = error    
        
    print('==> ', t, q[:2], np.rad2deg(q[2]))
    
    returnCode, pos = sim.simxGetObjectPosition(clientID, robotHandle, -1, sim.simx_opmode_oneshot_wait)        
    print('Pos: ', pos)

    returnCode, ori = sim.simxGetObjectOrientation(clientID, robotHandle, -1, sim.simx_opmode_oneshot_wait)
    print('Ori: ', np.rad2deg(ori))
        
    sim.simxSetJointTargetVelocity(clientID, wheel1, 0, sim.simx_opmode_oneshot_wait)
    sim.simxSetJointTargetVelocity(clientID, wheel2, 0, sim.simx_opmode_oneshot_wait)
    sim.simxSetJointTargetVelocity(clientID, wheel3, 0, sim.simx_opmode_oneshot_wait)
        
    # Now close the connection to CoppeliaSim:
    sim.simxFinish(clientID)
    
else:
    print ('Failed connecting to remote API server')
    
print ('Program ended')

Program started
Connected to remote API server
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[-1.77815207e-06  1.51679330e-06  1.15855028e-05]
[-1.77815207e-06  1.51679330e-06  1.15855028e-05]
[-1.77815207e-06  1.51679330e-06  1.15855028e-05]
[-1.77815207e-06  1.51679330e-06  1.15855028e-05]
[-1.77815207e-06  1.51679330e-06  1.15855028e-05]
[-1.77815207e-06  1.51679330e-06  1.15855028e-05]
[-1.77815207e-06  1.51679330e-06  1.15855028e-05]
[-1.77815207e-06  1.51679330e-06  1.15855028e-05]
[3.24481204e-02 2.82319684e-06 1.21941921e-05]
[3.24481204e-02 2.82319684e-06 1.21941921e-05]
[3.24481204e-02 2.82319684e-06 1.21941921e-05]
[3.24481204e-02 2.82319684e-06 1.21941921e-05]
[3.24481204e-02 2.82319684e-06 1.21941921e-05]
[3.24481204e-02 2.82319684e-06 1.21941921e-05]
[3.24481204e-02 2.82319684e-06 1.21941921e-05]
[3.24481204e-02 2.82319684e-06 1.21941921e-05]
[3.24481204e-02 2.82319684e-06 1.21941921e-05]
[3.24481204e-02 2.82319684e-06 1.21941921e-05]
[ 8.67645890e-02 -2.21229639

# Não-holonômico (Pioneer - diferencial)

In [ ]:
####################################################################################
#                                                                                  #
#                 LEMBRE-SE QUE A SIMULAÇÃO DEVE ESTAR EM EXECUÇÃO!                #
#                                                                                  #
####################################################################################

print ('Program started')
sim.simxFinish(-1) # just in case, close all opened connections
clientID=sim.simxStart('127.0.0.1',19999,True,True,5000,5) # Connect to CoppeliaSim

if clientID!=-1:
    print ('Connected to remote API server')

    robotname = 'Pioneer_p3dx'
    returnCode, robotHandle = sim.simxGetObjectHandle(clientID, robotname, sim.simx_opmode_oneshot_wait)     
        
    returnCode, l_wheel = sim.simxGetObjectHandle(clientID, robotname + '_leftMotor', sim.simx_opmode_oneshot_wait)
    returnCode, r_wheel = sim.simxGetObjectHandle(clientID, robotname + '_rightMotor', sim.simx_opmode_oneshot_wait)    
           
    # Específico do robô
    # https://www.generationrobots.com/media/Pioneer3DX-P3DX-RevA.pdf
    # L = 0.381   # Metros
    # r = 0.0975  # Metros
    
    L = 0.331
    r = 0.09751
    
    # Velocidade desejada (linear, angular)
    v = .3
    w = np.deg2rad(10)

    # Cinemática Inversa
    wr = ((2.0*v) + (w*L))/(2.0*r)
    wl = ((2.0*v) - (w*L))/(2.0*r)    
    u = np.array([wr, wl])

    # Enviando velocidades
    sim.simxSetJointTargetVelocity(clientID, l_wheel, wl, sim.simx_opmode_oneshot_wait)
    sim.simxSetJointTargetVelocity(clientID, r_wheel, wr, sim.simx_opmode_oneshot_wait)
    
    q = np.array([0, 0, 0])
    
    t = 0
    # Lembrar de habilitar o 'Real-time mode'
    startTime=time.time()
    lastTime = startTime
    while t < 10:
        
        now = time.time()
        dt = now - lastTime

        # Cinemática Direta
        Mdir = np.array([[r*np.cos(q[2])/2, r*np.cos(q[2])/2], [r*np.sin(q[2])/2, r*np.sin(q[2])/2], [r/L, -r/L]])
        q = q + (Mdir @ u)*dt
        
        t = t + dt        
        lastTime = now
    
    print('==> ', t, q[:2], np.rad2deg(q[2]))
    
    returnCode, pos = sim.simxGetObjectPosition(clientID, robotHandle, -1, sim.simx_opmode_oneshot_wait)        
    print('Pos: ', pos)

    returnCode, ori = sim.simxGetObjectOrientation(clientID, robotHandle, -1, sim.simx_opmode_oneshot_wait)
    print('Ori: ', np.rad2deg(ori))    
    
    sim.simxSetJointTargetVelocity(clientID, r_wheel, 0, sim.simx_opmode_oneshot_wait)
    sim.simxSetJointTargetVelocity(clientID, l_wheel, 0, sim.simx_opmode_oneshot_wait)
        
    # Now close the connection to CoppeliaSim:
    sim.simxFinish(clientID)
    
else:
    print ('Failed connecting to remote API server')
    
print ('Program ended')

# Para praticar

- Tentar utilizar o modelo do youBot (Kuka) e fazer uma navegação/controle simples
- Tentar utilizar um modelo do tipo Ackermann (e.g., Manta) e fazer uma navegação/controle simples